# TCL File Generated by Component Editor 14.0
# Mon Jul 20 11:25:20 EDT 2015
# DO NOT MODIFY


# 
# AHB_slave "AHB slave" v2.0
#  2015.07.20.11:25:20
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module AHB_slave
# 
set_module_property DESCRIPTION ""
set_module_property NAME AHB_slave
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "AHB slave"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AHB_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AHB_slave.sv SYSTEM_VERILOG PATH AHB_slave.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL AHB_slave
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AHB_slave.sv SYSTEM_VERILOG PATH AHB_slave.sv


# 
# parameters
# 
add_parameter ADDRESSWIDTH INTEGER 32
set_parameter_property ADDRESSWIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESSWIDTH DISPLAY_NAME ADDRESSWIDTH
set_parameter_property ADDRESSWIDTH TYPE INTEGER
set_parameter_property ADDRESSWIDTH UNITS None
set_parameter_property ADDRESSWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESSWIDTH HDL_PARAMETER true
add_parameter DATAWIDTH INTEGER 32
set_parameter_property DATAWIDTH DEFAULT_VALUE 32
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAWIDTH HDL_PARAMETER true
add_parameter NUMREGS INTEGER 8
set_parameter_property NUMREGS DEFAULT_VALUE 8
set_parameter_property NUMREGS DISPLAY_NAME NUMREGS
set_parameter_property NUMREGS TYPE INTEGER
set_parameter_property NUMREGS UNITS None
set_parameter_property NUMREGS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMREGS HDL_PARAMETER true
add_parameter REGWIDTH INTEGER 32
set_parameter_property REGWIDTH DEFAULT_VALUE 32
set_parameter_property REGWIDTH DISPLAY_NAME REGWIDTH
set_parameter_property REGWIDTH TYPE INTEGER
set_parameter_property REGWIDTH UNITS None
set_parameter_property REGWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REGWIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end u_addr u_addr Input ADDRESSWIDTH
add_interface_port conduit_end u_read_data u_read_data Output DATAWIDTH
add_interface_port conduit_end display_data display_data Output DATAWIDTH
add_interface_port conduit_end rdwr_address rdwr_address Input ADDRESSWIDTH
add_interface_port conduit_end add_data_sel add_data_sel Input 1


# 
# connection point ahb_slave
# 
add_interface ahb_slave ahb end
set_interface_property ahb_slave associatedClock clock
set_interface_property ahb_slave associatedReset reset
set_interface_property ahb_slave ENABLED true
set_interface_property ahb_slave EXPORT_OF ""
set_interface_property ahb_slave PORT_NAME_MAP ""
set_interface_property ahb_slave CMSIS_SVD_VARIABLES ""
set_interface_property ahb_slave SVD_ADDRESS_GROUP ""

add_interface_port ahb_slave HSEL hsel Input 1
add_interface_port ahb_slave HADDR haddr Input ADDRESSWIDTH
add_interface_port ahb_slave HWRITE hwrite Input 1
add_interface_port ahb_slave HSIZE hsize Input 3
add_interface_port ahb_slave HBURST hburst Input 3
add_interface_port ahb_slave HPROT hprot Input 4
add_interface_port ahb_slave HTRANS htrans Input 2
add_interface_port ahb_slave HREADY hreadyin Input 1
add_interface_port ahb_slave HWDATA hwdata Input DATAWIDTH
add_interface_port ahb_slave HREADYOUT hready Output 1
add_interface_port ahb_slave HRESP hresp Output 2
add_interface_port ahb_slave HRDATA hrdata Output DATAWIDTH

