# TCL File Generated by Component Editor 14.0
# Mon Aug 10 15:03:08 EDT 2015
# DO NOT MODIFY


# 
# avalon2ahb_bridge "avalon to ahb bridge" v2.0
#  2015.08.10.15:03:08
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module avalon2ahb_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon2ahb_bridge
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "avalon to ahb bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_ahb_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_ahb_bridge.sv SYSTEM_VERILOG PATH avalon_ahb_bridge.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_ahb_bridge
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_ahb_bridge.sv SYSTEM_VERILOG PATH avalon_ahb_bridge.sv


# 
# parameters
# 
add_parameter AVALON_ADDRESSWIDTH INTEGER 5
set_parameter_property AVALON_ADDRESSWIDTH DEFAULT_VALUE 5
set_parameter_property AVALON_ADDRESSWIDTH DISPLAY_NAME AVALON_ADDRESSWIDTH
set_parameter_property AVALON_ADDRESSWIDTH TYPE INTEGER
set_parameter_property AVALON_ADDRESSWIDTH UNITS None
set_parameter_property AVALON_ADDRESSWIDTH HDL_PARAMETER true
add_parameter ADDRESSWIDTH INTEGER 32
set_parameter_property ADDRESSWIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESSWIDTH DISPLAY_NAME ADDRESSWIDTH
set_parameter_property ADDRESSWIDTH TYPE INTEGER
set_parameter_property ADDRESSWIDTH UNITS None
set_parameter_property ADDRESSWIDTH HDL_PARAMETER true
add_parameter DATAWIDTH INTEGER 32
set_parameter_property DATAWIDTH DEFAULT_VALUE 32
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave address address Input AVALON_ADDRESSWIDTH
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input DATAWIDTH
add_interface_port avalon_slave waitrequest waitrequest Output 1
add_interface_port avalon_slave readdatavalid readdatavalid Output 1
add_interface_port avalon_slave readdata readdata Output DATAWIDTH
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ahb_master
# 
add_interface ahb_master ahb start
set_interface_property ahb_master associatedClock clock
set_interface_property ahb_master associatedReset reset
set_interface_property ahb_master ENABLED true
set_interface_property ahb_master EXPORT_OF ""
set_interface_property ahb_master PORT_NAME_MAP ""
set_interface_property ahb_master CMSIS_SVD_VARIABLES ""
set_interface_property ahb_master SVD_ADDRESS_GROUP ""

add_interface_port ahb_master HRDATA hrdata Input DATAWIDTH
add_interface_port ahb_master HREADY hready Input 1
add_interface_port ahb_master HRESP hresp Input 2
add_interface_port ahb_master HBURST hburst Output 3
add_interface_port ahb_master HSIZE hsize Output 3
add_interface_port ahb_master HTRANS htrans Output 2
add_interface_port ahb_master HSEL hsel Output 1
add_interface_port ahb_master HPROT hprot Output 4
add_interface_port ahb_master HADDR haddr Output ADDRESSWIDTH
add_interface_port ahb_master HWDATA hwdata Output DATAWIDTH
add_interface_port ahb_master HWRITE hwrite Output 1
add_interface_port ahb_master HREADYIN hreadyin Output 1

