# TCL File Generated by Component Editor 14.0
# Mon Aug 10 14:23:43 EDT 2015
# DO NOT MODIFY


# 
# ahb_master_slave_2 "ahb master and slave version 2" v2.0
#  2015.08.10.14:23:43
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module ahb_master_slave_2
# 
set_module_property DESCRIPTION ""
set_module_property NAME ahb_master_slave_2
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "ahb master and slave version 2"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top_level
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file top_level.sv SYSTEM_VERILOG PATH top_level.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL top_level
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file top_level.sv SYSTEM_VERILOG PATH top_level.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end add_data_sel add_data_sel Input 1
add_interface_port conduit_end display_data display_data Output 32
add_interface_port conduit_end rdwr_address rdwr_address Input 16


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink HRESETn reset_n Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink HCLK clk Input 1


# 
# connection point ahb_slave
# 
add_interface ahb_slave ahb end
set_interface_property ahb_slave associatedClock clock_sink
set_interface_property ahb_slave associatedReset reset_sink
set_interface_property ahb_slave ENABLED true
set_interface_property ahb_slave EXPORT_OF ""
set_interface_property ahb_slave PORT_NAME_MAP ""
set_interface_property ahb_slave CMSIS_SVD_VARIABLES ""
set_interface_property ahb_slave SVD_ADDRESS_GROUP ""

add_interface_port ahb_slave slave_HADDR haddr Input 32
add_interface_port ahb_slave slave_HBURST hburst Input 3
add_interface_port ahb_slave slave_HPROT hprot Input 4
add_interface_port ahb_slave slave_HSIZE hsize Input 3
add_interface_port ahb_slave slave_HTRANS htrans Input 2
add_interface_port ahb_slave slave_HWDATA hwdata Input 32
add_interface_port ahb_slave slave_HWRITE hwrite Input 1
add_interface_port ahb_slave slave_HRDATA hrdata Output 32
add_interface_port ahb_slave slave_HREADYOUT hready Output 1
add_interface_port ahb_slave slave_HRESP hresp Output 2
add_interface_port ahb_slave slave_HSEL hsel Input 1
add_interface_port ahb_slave slave_HREADY hreadyin Input 1


# 
# connection point ahb_master
# 
add_interface ahb_master ahb start
set_interface_property ahb_master associatedClock clock_sink
set_interface_property ahb_master associatedReset reset_sink
set_interface_property ahb_master ENABLED true
set_interface_property ahb_master EXPORT_OF ""
set_interface_property ahb_master PORT_NAME_MAP ""
set_interface_property ahb_master CMSIS_SVD_VARIABLES ""
set_interface_property ahb_master SVD_ADDRESS_GROUP ""

add_interface_port ahb_master master_HADDR haddr Output 32
add_interface_port ahb_master master_HBURST hburst Output 3
add_interface_port ahb_master master_HPROT hprot Output 4
add_interface_port ahb_master master_HSIZE hsize Output 3
add_interface_port ahb_master master_HTRANS htrans Output 2
add_interface_port ahb_master master_HWDATA hwdata Output 32
add_interface_port ahb_master master_HWRITE hwrite Output 1
add_interface_port ahb_master master_HRDATA hrdata Input 32
add_interface_port ahb_master master_HREADY hready Input 1
add_interface_port ahb_master master_HRESP hresp Input 2
add_interface_port ahb_master master_HREADYIN hreadyin Output 1
add_interface_port ahb_master master_HSEL hsel Output 1

